services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-playground-api:latest
    container_name: backend-playground-api
    restart: unless-stopped
    ports:
      - "8000:8000"

# TODO: Uncomment this section if we want to use a PostgreSQL database
#  postgres:
#    image: postgres:latest
#    container_name: ${DB_CONTAINER_NAME:-db-playground}
#    restart: always
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: token
#      POSTGRES_DB: car_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./migrations:/docker-entrypoint-initdb.d
