site_name: Backend Playground
theme:
  name: material
  font:
    text: Questrial
    code: Roboto Mono
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Toggle light mode
      primary: light blue
      accent: cyan
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Toggle dark mode
      primary: blue
      accent: indigo
  nav:
    - Home: index.md
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.suggest
  nav_style: primary
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - go
    - bash
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences # Enables syntax highlighting for code blocks
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true # Enables tabbed code sections
extra_css:
  - styles/custom.css
copyright: Copyright &copy; 2025 Joaquin Franco
