name: Integration Test

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/integration-test.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t aeternum-api:test .

      - name: Start API Container
        run: |
          docker run -d --rm --name aeternum-api-integration -p 8000:8000 aeternum-api:test
          sleep 5

      - name: Wait for API to be Ready
        run: |
          for i in {1..10}; do
            curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/healthz | grep 200 && break
            echo "Waiting for API..."
            sleep 2
          done

      - name: Run integration test
        run: |
          echo "Testing /health endpoint..."
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/healthz | grep 200 || exit 1

      - name: Stop API container
        if: always()
        run: docker stop aeternum-api-integration
