name: Testing

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "**.py"
      - ".github/workflows/testing.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
      - "**.py"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run Pytest
        run: |
          just pytest -vv
